class CitiesData {
  // todas las ciudades de mexico
  static List<String> cities = [
    'Baja California',
    'Baja California Sur',
    'Chiapas',
    'Ciudad de México',
    'Coahuila',
    'Colima',
    'Durango',
    'Guanajuato',
    'Jalisco',
    'México',
    'Michoacán',
    'Nuevo Leon',
    'Puebla',
    'Querétaro',
    'Sinaloa',
    'Yucatán',
  ];

  static Map<String, List> municipiosPorCiudad = {
    'Baja California': [
      'Tijuana',
      'Mexicali',
      'Ensenada',
      'Playas de Rosarito',
      'Tecate',
    ],
    'Baja California Sur': [
      'La Paz',
      'Los Cabos',
      'Comondú',
      'Mulegé',
      'Loreto',
    ],
    'Chiapas': [
      'Tuxtla Gutiérrez',
      'Tapachula',
      'San Cristóbal de las Casas',
      'Palenque',
      'Comitán de Domínguez',
    ],
    'Ciudad de México': [
      'Álvaro Obregón',
      'Azcapotzalco',
      'Benito Juárez',
      'Coyoacán',
      'Cuajimalpa de Morelos',
    ],
    'Coahuila': [
      'Saltillo',
      'Torreón',
      'Monclova',
      'Piedras Negras',
      'Acuña',
    ],
    'Colima': [
      'Colima',
      'Manzanillo',
      'Tecomán',
      'Villa de Álvarez',
      'Minatitlán',
    ],
    'Durango': [
      'Durango',
      'Gómez Palacio',
      'Lerdo',
      'Pueblo Nuevo',
      'Canatlán',
    ],
    'Guanajuato': [
      'León',
      'Irapuato',
      'Celaya',
      'Salamanca',
      'Guanajuato',
    ],
    'Jalisco': [
      'Guadalajara',
      'Zapopan',
      'Tlaquepaque',
      'Tonalá',
      'Tlajomulco de Zúñiga',
    ],
    'México': [
      'Ecatepec de Morelos',
      'Nezahualcóyotl',
      'Naucalpan de Juárez',
      'Toluca',
      'Tlalnepantla de Baz',
    ],
    'Michoacán': [
      'Morelia',
      'Uruapan',
      'Lázaro Cárdenas',
      'Zamora',
      'Pátzcuaro',
    ],
    'Nuevo Leon': [
      'Monterrey',
      'Guadalupe',
      'San Nicolás de los Garza',
      'Apodaca',
      'General Escobedo',
    ],
    'Puebla': [
      'Puebla',
      'Tehuacán',
      'San Martín Texmelucan',
      'Cholula',
      'Izúcar de Matamoros',
    ],
    'Querétaro': [
      'Querétaro',
      'San Juan del Río',
      'Corregidora',
      'El Marqués',
      'Cadereyta de Montes',
    ],
    'Sinaloa': [
      'Culiacán',
      'Mazatlán',
      'Los Mochis',
      'Guasave',
      'Ahome',
    ],
    'Yucatán': [
      'Mérida',
      'Kanasín',
      'Progreso',
      'Tizimín',
      'Umán',
    ],
  };
}
